version: '2'
services:
    music_finder-mysql:
        container_name: music_finder-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/music_finder/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=music_finder
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
